replicaCount: 1

frontend:
  image:
    repository: my-frontend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

backend:
  image:
    repository: my-backend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

mysql:
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 8Gi


redis:
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi


ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: task2.local
      paths:
        - path: /api/tasks
          pathType: Prefix
          backend:
            serviceName: backend
            servicePort: 5000
        - path: /
          pathType: Prefix
          backend:
            serviceName: frontend
            servicePort: 80
        
  tls: []

configMap:
  enabled: true
  data:
    MYSQL_USER: "root" 
    MYSQL_DB: "tasks_db"
    REDIS_PORT: "6379"  
    FLASK_ENV: "development"
    API_URL: ""

secret:
  enabled: true
  data:
    MYSQL_PASSWORD: "cGFzcw=="
    MYSQL_ROOT_PASSWORD: "cGFzcw=="
