replicaCount: 1 # не поправлена общая реплика для БЕ и ФЕ

frontend:
  image:
    repository: piktakatya/my-frontend
    tag: "{{ .Values.imageTag }}"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

backend:
  image:
    repository: piktakatya/my-backend
    tag: "{{ .Values.imageTag }}"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

mysql:
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  env:
     # почему напрямую настриваются эти вары, если ниже по файлу секрет создается с ними?
     MYSQL_PASSWORD: "cGFzcw==" # секреты наружу, лучше использовать secretRef https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
     MYSQL_ROOT_PASSWORD: "cGFzcw=="
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 8Gi


redis:
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi


ingress:
  enabled: true
  tls: [] # на что это влияет?

configMap:
  enabled: true
  data:
    MYSQL_USER: "root" 
    MYSQL_DB: "tasks_db"
    REDIS_PORT: "6379"  
    FLASK_ENV: "development"
    API_URL: "" # почему это пусто?
    # FE_HOST: ?

secret: # как и говорил, лучше создать руками секрет и ссылаться на него, вместо ведения его в values.yml файле
  enabled: true
  data:
    MYSQL_PASSWORD: "cGFzcw=="
    MYSQL_ROOT_PASSWORD: "cGFzcw=="
