{{- if .Values.persistence.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.redis.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.redis.size }}
  {{- if .Values.persistence.redis.storageClass }}
  storageClassName: {{ .Values.persistence.redis.storageClass }}
  {{- end }}
{{- end }}