{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: task2-secret
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}